### ISSUE TITLE
Main website nav order is incorrect

### ISSUE THREAD

**Issue by Erioldoesdesign** [simplysecure/user_project_website#51]
The main website nav order is not correct on the URL https://user-project.superbloom.design/ 

However, on the URL https://subtle-medovik-58f1c6.netlify.app/findings/ the menu order and styling is correct

See a screen recording of the incorrect menu structure here:

https://github.com/simplysecure/user_project_website/assets/11681324/e3453d59-c6cf-4d57-a5cd-a71fddbf6786

This may be fixed by making sure that the user-superbloom url properly redirects to the netlify.app link but we'd like to maintain the url naming of user-project etc. if possible.

**Comment by SaptakS** [comment]
Do we still want to have the ordering that is mentioned in the Miro document?
