### ISSUE TITLE
Match the logo styling across URL's

### ISSUE THREAD

**Issue by Erioldoesdesign** [simplysecure/user_project_website#53]
There are three different logos showing across various urls.

Correct and visible when using any nav link and displaying the netlify url:
![Screenshot 2023-06-27 at 13 46 30](https://github.com/simplysecure/user_project_website/assets/11681324/ecf18fa9-02d9-4b25-b5d3-4498aaf2b8dc)

Incorrect:
![Screenshot 2023-06-27 at 13 46 37](https://github.com/simplysecure/user_project_website/assets/11681324/869001ae-9af0-435a-9e35-f26e9bcf8900)
![Screenshot 2023-06-27 at 13 36 52](https://github.com/simplysecure/user_project_website/assets/11681324/ee06e6f5-f34a-4db7-a0c5-067cbe1f721f)
The cupper logo shows on the default netlify url (https://subtle-medovik-58f1c6.netlify.app/) and the large USER logo shows on the correct project URL https://user-project.superbloom.design/

**Comment by SaptakS** [comment]
This should also be fixed by https://github.com/simplysecure/user_project_website/issues/52#issuecomment-1611312185

**Comment by Erioldoesdesign** [comment]
Fixed!
