### ISSUE TITLE
Images not displaying behind text

### ISSUE THREAD

**Issue by Erioldoesdesign** [simplysecure/user_project_website#54]
**Existing:** 

![Screenshot 2023-06-27 at 13 43 33](https://github.com/simplysecure/user_project_website/assets/11681324/c4826a92-343b-4524-ab68-03264b7d20fc)

----

**Mockup:**

![Screenshot 2023-06-27 at 13 49 34](https://github.com/simplysecure/user_project_website/assets/11681324/ac729e94-8784-4c1a-ba83-98ddce918ab9)

**Comment by oilsinwater** [comment]
Working now so closing.
