### ISSUE TITLE
When bookmarked label is 'cupper'

### ISSUE THREAD

**Issue by Erioldoesdesign** [simplysecure/user_project_website#55]
When you bookmark the URL https://user-project.superbloom.design/

It gets added as 'cupper'

Image: ![Screenshot 2023-06-27 at 13 40 28](https://github.com/simplysecure/user_project_website/assets/11681324/001ddb5d-e11b-4a5f-afad-64e6502a0d95)

**Comment by SaptakS** [comment]
For me it is showing "Usable Software Ecosystem Research" right now. Might have been fixed by https://github.com/simplysecure/user_project_website/issues/52#issuecomment-1611312185 ?

**Comment by Erioldoesdesign** [comment]
Yeah was my caching issue so fixed!
