### ISSUE TITLE
Styling of nav links is old cupper style

### ISSUE THREAD

**Issue by Erioldoesdesign** [simplysecure/user_project_website#56]
This may get fixed with some URL moving and fixing but the https://user-project.superbloom.design/ url currently has the old little bookmark style on nav links when they should be '>>' arrows like what exists on the netlify url https://subtle-medovik-58f1c6.netlify.app/findings/

![Screenshot 2023-06-27 at 13 37 11](https://github.com/simplysecure/user_project_website/assets/11681324/43c4c7af-015d-43e4-937f-d798172e3392)
![Screenshot 2023-06-27 at 13 37 21](https://github.com/simplysecure/user_project_website/assets/11681324/f38aa11d-400e-4220-b78a-ff970218e7d3)
![Screenshot 2023-06-27 at 13 37 26](https://github.com/simplysecure/user_project_website/assets/11681324/ce3a02c0-ba5d-47c4-8ce0-cc54612fb9d8)

**Comment by SaptakS** [comment]
I think this is also fixed by https://github.com/simplysecure/user_project_website/issues/52#issuecomment-1611312185

**Comment by Erioldoesdesign** [comment]
Yep fixed!
