### ISSUE TITLE
Scroll menu is small, any way to make it a little larger?

### ISSUE THREAD

**Issue by georgiamoon** [simplysecure/user_project_website#60]
Some ideas:
- Reducing text size on the blurb?
- reducing text size in the menu area
- tweaking padding?

Just brainstorming, but open to any ideas!

**Comment by Erioldoesdesign** [comment]
Happy for text size on the blurb to be reduced and also the menu stylings to be reduced too.

If we had dev time we could also make a mini 'shrinking' version of the top left logo but ehh time is not on our side now

**Comment by Erioldoesdesign** [comment]
Closed by accident is this the css to change font size @SaptakS ?
<img width="402" alt="Screenshot 2023-06-29 at 10 42 17" src="https://github.com/simplysecure/user_project_website/assets/11681324/2421e1f1-7ae8-4556-a0a4-c193044ff0eb">

**Comment by Erioldoesdesign** [comment]
Messing around with some CSS in inspect element I got this:
<img width="1296" alt="Screenshot 2023-06-29 at 11 34 07" src="https://github.com/simplysecure/user_project_website/assets/11681324/807354a8-33a9-44b7-9d5b-b39c148f6648">

Changing the line height in here: <img width="313" alt="Screenshot 2023-06-29 at 11 33 50" src="https://github.com/simplysecure/user_project_website/assets/11681324/e1e80007-8823-4412-addf-9993f404b1f0">

Making font size 'small' here <img width="396" alt="Screenshot 2023-06-29 at 11 29 54" src="https://github.com/simplysecure/user_project_website/assets/11681324/a86d7059-cde6-454a-ae11-38b7ae8da2bf">

Making intro text smaller here: <img width="417" alt="Screenshot 2023-06-29 at 11 27 12" src="https://github.com/simplysecure/user_project_website/assets/11681324/61716310-1b54-455d-b7bb-c65c02688a21">

Making h3 headings in nav smaller here:
<img width="219" alt="Screenshot 2023-06-29 at 11 25 42" src="https://github.com/simplysecure/user_project_website/assets/11681324/1ccab003-8d9f-4022-ae6a-5b7aad6a1c50">

**Comment by SaptakS** [comment]
@Erioldoesdesign I think reducing the font-sizes make sense to me. I think the size of the logo can also be reduced a bit, since that is taking up a lot of the space, in case that is not against the design that is wanted.

**Comment by georgiamoon** [comment]
that all sounds good to me! @SaptakS I was chatting with @Erioldoesdesign earlier and they weren't sure if the css they were editing was the right css, does that seem right? Or can you help with proposed edits?

**Comment by SaptakS** [comment]
I think what @Erioldoesdesign has proposed above are all correct. Only instead of using `small` for `font-size`, I would say, use a specific `rem` value, something like `0.5rem` maybe? The other things we can do I think is reduce the padding a bit (it's a little too much right now maybe?) and reducing the logo size. I can put some dev hours tomorrow to create a PR addressing the same.

**Comment by Erioldoesdesign** [comment]
> I think what @Erioldoesdesign has proposed above are all correct. Only instead of using `small` for `font-size`, I would say, use a specific `rem` value, something like `0.5rem` maybe? The other things we can do I think is reduce the padding a bit (it's a little too much right now maybe?) and reducing the logo size. I can put some dev hours tomorrow to create a PR addressing the same.

yes yes using rem sounds good to me :D as well as reducing the logo size
